INSERT INTO customer (id, email, password, username, is_disabled) VALUES (1,'hubert@hubert', '$2a$12$f1fs0PaxJScTaB6NexA0juQyOTVa3KiEfCy1s4Vgpam6a2DHj5Ojm', 'hubert', 0);
INSERT INTO authorities (id, name, customer_id) VALUES (1, "ROLE_ADMIN", 1);

-- COURSE ----

insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (1, '17vv7A2QUPBRvq3VdzVAtQsJ7S59gC7z3o', 'http://dummyimage.com/247x100.png/5fa2dd/ffffff', 'Big Eden', 1, false, 1);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (2, '1CC35smRor9zgCXbzsEycCCd1eyqWBETDT', 'http://dummyimage.com/156x100.png/ff4444/ffffff', 'Last Days of Pompeii, The', 2, false, 2);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (3, '1EktT48sSdHUpDFD2LTMA3nGW2ksiSoR4Z', 'http://dummyimage.com/143x100.png/dddddd/000000', 'Unidentified Flying Oddball (a.k.a. Spaceman and King Arthur, The) (a.k.a. Spaceman in King Arthur''s Court, A)', 3, false, 3);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (4, '1LaBkdnF5bHt27Zkyc2kugoxnCNSARTQdR', 'http://dummyimage.com/181x100.png/cc0000/ffffff', 'Branded to Kill (Koroshi no rakuin)', 4, true, 4);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (5, '1Awoa5NSAsRGW7NYvVBLMvcUJrbhgxAcDb', 'http://dummyimage.com/168x100.png/dddddd/000000', 'The Girl from the Marsh Croft', 5, false, 5);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (6, '1BrUEjBwtmqEkcFHNCBt9Bv4srxCM2pHDu', 'http://dummyimage.com/155x100.png/ff4444/ffffff', 'Conspiracy Theory', 6, false, 6);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (7, '19Y6K4EWTm5vckAA3L7k8Gqb1wDtfdHUhh', 'http://dummyimage.com/114x100.png/5fa2dd/ffffff', 'Patsy', 7, false, 7);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (8, '1K43a8VgPspLc2BDbdu4zH1avwvEGQxJ68', 'http://dummyimage.com/145x100.png/ff4444/ffffff', 'Monogamy ', 8, false, 8);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (9, '1DfGEok3qDoBqT8L1YECTuPK3Mb12eFCk9', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff', 'Theatre of Blood', 9, false, 9);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (10, '1FDhFqV8NYjdSwCHdrWRdJ6cYUsdDW9CN3', 'http://dummyimage.com/239x100.png/5fa2dd/ffffff', 'How to Cook Your Life', 10, true, 10);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (11, '1N5v3hnQLu3SeUxJaUHVuPhL8Pmz7cE17', 'http://dummyimage.com/125x100.png/dddddd/000000', 'Wrong Side Up (Pribehy obycejneho silenstvi)', 11, true, 11);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (12, '1GE432wgaQX4TFmVVBZNTqRcz7fdWY4X7P', 'http://dummyimage.com/205x100.png/5fa2dd/ffffff', 'Spontaneous Combustion', 12, false, 12);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (13, '1FofbaTQ6H2xy1GBhc8xMHhjnpd4T8xTYF', 'http://dummyimage.com/102x100.png/5fa2dd/ffffff', 'In Fear', 13, false, 13);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (14, '1Js7iKLcQimNiYUg9Yjt13toaG8vvuRtGu', 'http://dummyimage.com/158x100.png/cc0000/ffffff', 'Animatrix, The', 14, false, 14);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (15, '1wvPia1DRUxi4Fk1TKyTnMXxgZK8tD2oX', 'http://dummyimage.com/151x100.png/dddddd/000000', 'Belle Starr', 15, true, 15);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (16, '1Rp1U5jWrxw793GiaHxgSGEeRu58XW9ys', 'http://dummyimage.com/197x100.png/cc0000/ffffff', 'Last of the Mohicans, The', 16, false, 16);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (17, '1APJDqsvpxqDzDkL11FAMtDx76RmVJWdLJ', 'http://dummyimage.com/166x100.png/5fa2dd/ffffff', 'Godzilla vs. Hedorah (Gojira tai Hedorâ) (Godzilla vs. The Smog Monster) ', 17, false, 17);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (18, '1BSxWMnjC7soUHzSLtpYWSy4gDLHaqzhqs', 'http://dummyimage.com/211x100.png/5fa2dd/ffffff', 'Daylight', 18, true, 18);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (19, '1PpiKneatNnLG1j7exctrHiwYX1u1MdevJ', 'http://dummyimage.com/156x100.png/5fa2dd/ffffff', 'Johnny Handsome', 19, false, 19);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (20, '1BpD48xQw455upQCd6bi8A1iCBzpM627sb', 'http://dummyimage.com/187x100.png/ff4444/ffffff', 'Comancheros, The', 20, true, 20);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (21, '1CznCxTZ9PuxzJ7Qp2pwGNkT6B4Jqq575G', 'http://dummyimage.com/230x100.png/dddddd/000000', 'Friends of God: A Road Trip with Alexandra Pelosi', 21, true, 21);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (22, '19TguwuAoApizBrGSFY71FmtP3taURb937', 'http://dummyimage.com/241x100.png/ff4444/ffffff', '2046', 22, true, 22);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (23, '1CWweSZMqXxuGUPPZF2Y3WXhd32xuxHiNx', 'http://dummyimage.com/182x100.png/5fa2dd/ffffff', 'Valley of the Bees (Údolí vcel)', 23, false, 23);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (24, '17wKyzBSDShLosj3EJkYFtBsmyngKmjLfD', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', 'Last Days in Vietnam', 24, false, 24);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (25, '1VgSQdGVCPmsrBiH4NvtpisWEbKPxedmt', 'http://dummyimage.com/218x100.png/ff4444/ffffff', 'Popeye', 25, false, 25);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (26, '1ZtQ8CtSE863hnkEHtUXcFTS5TLp9KQDa', 'http://dummyimage.com/222x100.png/cc0000/ffffff', 'Making Mr. Right', 26, false, 26);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (27, '14kVvAWC4LVDovBif8K6jVp7gLmhHJsrcV', 'http://dummyimage.com/152x100.png/ff4444/ffffff', 'Piano Teacher, The (La pianiste)', 27, true, 27);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (28, '14BAxRYQvqAB3YCJSYaG9GsrdBUwtp1rBG', 'http://dummyimage.com/190x100.png/5fa2dd/ffffff', 'The Sky Dragon', 28, false, 28);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (29, '1FfJ9U3SWPg7oTzk6pQrR5nbqCZAWx8iYa', 'http://dummyimage.com/174x100.png/dddddd/000000', 'Kennedys, The', 29, false, 29);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (30, '15G3FaUab4D8ZuXYsZdDrg5Keb4t8sh7um', 'http://dummyimage.com/247x100.png/ff4444/ffffff', 'Immortel (ad vitam) (Immortal)', 30, true, 30);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (31, '1N4XGn9ETvhFFpkApPo9PNkdp1hS1hE3Es', 'http://dummyimage.com/133x100.png/dddddd/000000', 'Unholy', 31, true, 31);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (32, '1MN65SCb7na2JpjnbGY5tsh8sJQZzWrJV7', 'http://dummyimage.com/232x100.png/cc0000/ffffff', 'Not Love, Just Frenzy (Más que amor, frenesí)', 32, false, 32);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (33, '19gu5pkdfdYfp7j5XhaZjrx4DZUZFdzV2h', 'http://dummyimage.com/139x100.png/cc0000/ffffff', 'My Sister Eileen', 33, false, 33);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (34, '1HwEVbxR6z4aGsjtCZ3JaQuaub1GmwAPsE', 'http://dummyimage.com/192x100.png/ff4444/ffffff', 'Dragon Ball Z: Broly - The Legendary Super Saiyan (Doragon bôru Z 8: Moetsukiro!! Nessen retsusen-chô gekisen)', 34, false, 34);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (35, '17xWtFTERnSgDQfQELaAYAwCGeowxSdYs4', 'http://dummyimage.com/164x100.png/dddddd/000000', 'Handmaid''s Tale, The', 35, true, 35);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (36, '1BepK6BvexX5KnHttrKSDGNaFfvefarGuF', 'http://dummyimage.com/110x100.png/dddddd/000000', 'Blood', 36, false, 36);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (37, '14a1nMtfdY38WoyGwg9HnDEPDcKaRmvsWc', 'http://dummyimage.com/114x100.png/5fa2dd/ffffff', 'Sintel', 37, false, 37);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (38, '1LdQmeJQZ3rxnXUcQdsRqR9DodVYkzpH9i', 'http://dummyimage.com/250x100.png/dddddd/000000', 'Quartet', 38, true, 38);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (39, '14dNXuKiUfdiLjJkMSwmBJ9YfmQtouboUc', 'http://dummyimage.com/145x100.png/5fa2dd/ffffff', 'Phantom, The', 39, true, 39);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (40, '1SUXboWhhUsLHFtrPMfVjsyhR7xxKR11q', 'http://dummyimage.com/243x100.png/cc0000/ffffff', 'Mean Girls', 40, true, 40);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (41, '14osF66JoP7dDZcJWoxRuCrwtS56hmiL5w', 'http://dummyimage.com/207x100.png/ff4444/ffffff', 'Craig Ferguson: Does This Need to Be Said?', 41, true, 41);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (42, '1Da2iXPCrJ82EmLm6B81A83EWyiJtVY1qu', 'http://dummyimage.com/249x100.png/ff4444/ffffff', 'Jönssonligan & den svarta diamanten', 42, true, 42);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (43, '12Hkf9xHGBd7rEs1fn8A5CCpjyZP9rxmpb', 'http://dummyimage.com/154x100.png/dddddd/000000', 'Angels and Insects', 43, true, 43);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (44, '1Nh64DeHvsAwzUTymtnEjT3TAD5GUqmaiC', 'http://dummyimage.com/103x100.png/ff4444/ffffff', 'Murder at the Gallop', 44, true, 44);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (45, '1LFYforX7Tp2MoNyRCMXhjfHsMF22RADia', 'http://dummyimage.com/239x100.png/5fa2dd/ffffff', 'Skylab, Le', 45, false, 45);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (46, '16HhKvze987TgFhKykfpSnhcPN3KcZMVA', 'http://dummyimage.com/202x100.png/ff4444/ffffff', 'Amati Girls, The', 46, true, 46);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (47, '1DsjCQbaVfEMsx5KivRHVWop2HRVh7WcvD', 'http://dummyimage.com/234x100.png/dddddd/000000', 'Man Behind the Gun, The', 47, true, 47);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (48, '14xBznY8w9tkT3CrQYUj7uGsZFVKEJqmfk', 'http://dummyimage.com/183x100.png/dddddd/000000', 'Hunter Prey', 48, true, 48);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (49, '1FxoEyMDet7oM6f6yrRPfSUVxhNstbgxCc', 'http://dummyimage.com/103x100.png/cc0000/ffffff', 'Le créateur ', 49, true, 49);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (50, '1MtNGbQQRmMBVLAyXhpwKQfWdZ4RdjELzD', 'http://dummyimage.com/243x100.png/cc0000/ffffff', 'Klimt', 50, false, 50);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (51, '1PGHi4hUThnwirrYG4UX5Mw8t7m3QX6eFg', 'http://dummyimage.com/110x100.png/dddddd/000000', 'Jack and Diane', 51, false, 51);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (52, '129hkzUvarHB7mrVMa28wq1pxS7Yk2HXd8', 'http://dummyimage.com/165x100.png/ff4444/ffffff', 'Inheritors, The (Siebtelbauern, Die)', 52, false, 52);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (53, '15jv8naKiyzsMWUvNsV5bnGSEY7FfsLsGw', 'http://dummyimage.com/101x100.png/dddddd/000000', 'Nightcap (Merci pour le chocolat)', 53, true, 53);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (54, '1UL8iTNBcPW7qJEfwUHAzS93ZBwYzkUmu', 'http://dummyimage.com/224x100.png/cc0000/ffffff', 'Agent Cody Banks', 54, true, 54);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (55, '1KZBY5R5CjC9UD91cLQmGLFHX7MBT7WJA1', 'http://dummyimage.com/239x100.png/dddddd/000000', 'Missing in America', 55, true, 55);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (56, '1L3dGVxPn4ogsuWx6SV5b72NpG7XH7YppA', 'http://dummyimage.com/215x100.png/5fa2dd/ffffff', 'Ballad of Narayama, The (Narayama bushiko)', 56, false, 56);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (57, '1A8AYchRRApUbGGfcx8FekxpXMfsa7fU3j', 'http://dummyimage.com/195x100.png/dddddd/000000', 'I Even Met Happy Gypsies (Skupljaci perja)', 57, false, 57);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (58, '1K6BxR3zbp7JEABTL519HGjaWjB9ecZDhk', 'http://dummyimage.com/180x100.png/cc0000/ffffff', 'North Face (Nordwand)', 58, true, 58);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (59, '16jha1fs1a1Vfg4qP4EPvx356Wdudekwak', 'http://dummyimage.com/223x100.png/dddddd/000000', 'Touch the Sound: A Sound Journey with Evelyn Glennie', 59, false, 59);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (60, '1EdMK4przsRUp97Uk6j6u5w8WrZTXYPwvC', 'http://dummyimage.com/159x100.png/5fa2dd/ffffff', 'Scoop', 60, false, 60);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (61, '12aEPEHyEykqqCeiRre8zRN4cU91CSrpGF', 'http://dummyimage.com/162x100.png/cc0000/ffffff', 'Quickie, The', 61, true, 61);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (62, '1GoxFocGaRzchbqZLi8Ds9WfKAghdqfXST', 'http://dummyimage.com/250x100.png/dddddd/000000', 'Guitar, The', 62, false, 62);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (63, '17s9EsseYp4cVHjKZvn4soFM97sML6z3n4', 'http://dummyimage.com/106x100.png/dddddd/000000', 'Cosmic Journey', 63, false, 63);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (64, '14cubHhcpHkN3ZeKwoaAanv5ks8ZHbjs1q', 'http://dummyimage.com/245x100.png/5fa2dd/ffffff', 'London', 64, false, 64);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (65, '1N2FPthU4yptHTUvN6yuJVwwx9GGvhV4BG', 'http://dummyimage.com/226x100.png/ff4444/ffffff', 'Witchfinder General (Conquerer Worm, The)', 65, true, 65);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (66, '1aje6sDFoAsTRogQ2g7t4ZiEzvyneiETi', 'http://dummyimage.com/152x100.png/dddddd/000000', 'King of Escape, The (Le roi de l''évasion)', 66, false, 66);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (67, '1K8FTkThQymf6FGJukXZXmxQM3XJiHWDTZ', 'http://dummyimage.com/132x100.png/cc0000/ffffff', 'Diary of a Chambermaid (Journal d''une femme de chambre, Le)', 67, true, 67);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (68, '17fHk2XdPHLFXUZYzw4RP6y1fNWmBcGDTM', 'http://dummyimage.com/157x100.png/dddddd/000000', 'Bronies: The Extremely Unexpected Adult Fans of My Little Pony', 68, false, 68);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (69, '17bniGn8oDtKGMcTgGxomcodVX94odnBXZ', 'http://dummyimage.com/189x100.png/ff4444/ffffff', 'Captivated', 69, true, 69);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (70, '16nhsq6fZ76BFUUFtJZpx4TfUDJZWzr9p2', 'http://dummyimage.com/237x100.png/cc0000/ffffff', 'Date Movie', 70, true, 70);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (71, '13sSomR6gCKHNScwcYEf2XqRSVbTRcFfHk', 'http://dummyimage.com/154x100.png/cc0000/ffffff', 'Eight Miles High (Das wilde Leben)', 71, false, 71);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (72, '1LakirAbreepYuxR9WHEQEQh3o5xSZnLno', 'http://dummyimage.com/119x100.png/cc0000/ffffff', '71: Into The Fire (Pohwasogeuro)', 72, true, 72);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (73, '1Aa8oTVKNCBReqTxQC9DTzeVY6znLEKdx6', 'http://dummyimage.com/116x100.png/5fa2dd/ffffff', 'Kismet', 73, false, 73);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (74, '153XXeAftcnQcRy4ekZMfyAfK9aKc4ZTav', 'http://dummyimage.com/213x100.png/dddddd/000000', 'Confessions from a Holiday Camp', 74, false, 74);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (75, '1PMJiEMZ2wwJCgZYLUiSs9sTSHFBcvwtJ1', 'http://dummyimage.com/225x100.png/cc0000/ffffff', 'Stella Does Tricks', 75, true, 75);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (76, '1jpVpZfGuW6bVimJkQstq871Jxe36DTLv', 'http://dummyimage.com/215x100.png/ff4444/ffffff', 'Bomb It', 76, true, 76);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (77, '19XKF61862MUSoaFwBQLWfK2cHic3iPJ2j', 'http://dummyimage.com/157x100.png/dddddd/000000', 'Them (Ils)', 77, false, 77);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (78, '15BZLZbBnK1A9agcRf97rKab3JQm1a8nHx', 'http://dummyimage.com/120x100.png/dddddd/000000', 'Man on a Ledge', 78, true, 78);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (79, '1CQjKfJnCaVBXTm51hrsUukXwjbKJyHDcS', 'http://dummyimage.com/219x100.png/cc0000/ffffff', 'Light at the Edge of the World, The', 79, false, 79);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (80, '1PGF6ygwkYspXdsEvQSFryMe7BpPGU93aM', 'http://dummyimage.com/131x100.png/dddddd/000000', 'Fast Times at Ridgemont High', 80, false, 80);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (81, '1F3vJv31fBzBxcRcjNYHC3WBnK4HiXjcRr', 'http://dummyimage.com/167x100.png/ff4444/ffffff', 'This Woman Is Dangerous', 81, false, 81);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (82, '1Bzoquj7Xr7WHQMVRFY9JhBeqBDnupmqdd', 'http://dummyimage.com/201x100.png/dddddd/000000', 'Donkey Skin (Peau d''âne)', 82, false, 82);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (83, '187Yt3dtMhuT2eMJKhckpqsucdXWxJZUWb', 'http://dummyimage.com/192x100.png/5fa2dd/ffffff', 'Goodbye World', 83, false, 83);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (84, '12PyFpMjgXurtGpZSLH2yVaKMR7SgfiUFQ', 'http://dummyimage.com/230x100.png/ff4444/ffffff', 'Sin Retorno', 84, true, 84);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (85, '17nVYCavdJrWSAqkP1jDPXszacfMj7cHZL', 'http://dummyimage.com/185x100.png/dddddd/000000', 'Matrix Revolutions, The', 85, true, 85);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (86, '1BVVmeUEg5QwHXurVmvUu3qT7BEcGt3k6A', 'http://dummyimage.com/168x100.png/cc0000/ffffff', 'Man of the World', 86, false, 86);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (87, '1HACvc7jQobX2VamveDHCeaKCZfB1oDDkk', 'http://dummyimage.com/198x100.png/5fa2dd/ffffff', 'Pee-wee''s Big Adventure', 87, false, 87);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (88, '1HZyo64SBcKHYkicD6AEoXk7Km8Lsseu4Y', 'http://dummyimage.com/142x100.png/ff4444/ffffff', 'The Underneath', 88, true, 88);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (89, '1KTsZW4EdYcUUowJtE8CrpTkyj3AG8PkWW', 'http://dummyimage.com/222x100.png/ff4444/ffffff', 'My Crazy Life (Mi vida loca)', 89, true, 89);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (90, '1Gk3cSxBsiNoGYhPccDzenthCxSj2xB3MY', 'http://dummyimage.com/137x100.png/ff4444/ffffff', 'The Merry Widow', 90, false, 90);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (91, '15AxQwyABTgC9Wqv6Vc5nNEwCR9kE93gmM', 'http://dummyimage.com/133x100.png/cc0000/ffffff', 'The Phantom Light', 91, false, 91);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (92, '1NhRWpvg7jaFWND8PDsvmAKYUFjp7nFQ3K', 'http://dummyimage.com/224x100.png/dddddd/000000', 'Leonard Cohen: I''m Your Man', 92, true, 92);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (93, '1AapXpT2DKBrNtqT7sQ6z8LUcmzsBDGX2B', 'http://dummyimage.com/106x100.png/dddddd/000000', 'Artois the Goat', 93, true, 93);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (94, '1K74xJEpKrjMuBP3fnCxx9UQPcVpwairUv', 'http://dummyimage.com/139x100.png/5fa2dd/ffffff', 'Leatherheads', 94, false, 94);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (95, '17HTCVwj2uy9DpfNS5Mo3gtvbUwBbk5dfp', 'http://dummyimage.com/232x100.png/ff4444/ffffff', 'Dinotopia', 95, false, 95);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (96, '112TiCrbwhNJ3kJs3FoK9DcP4VJeiXkZW8', 'http://dummyimage.com/194x100.png/cc0000/ffffff', 'Experiment in Terror', 96, false, 96);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (97, '1E8YTzsu4127aPQQ4tsAGytDLdZ66LYJyR', 'http://dummyimage.com/168x100.png/ff4444/ffffff', 'Zero de conduite (Zero for Conduct) (Zéro de conduite: Jeunes diables au collège)', 97, true, 97);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (98, '16SRzWe3qs2p6BmcPoPaPE1AoCiCBwu63R', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff', 'It Happened Here', 98, true, 98);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (99, '1MLFSJe2x1uBCscxn7jJNLMtsXmF1611vT', 'http://dummyimage.com/226x100.png/ff4444/ffffff', 'Elizabeth: The Golden Age', 99, true, 99);
insert into course (id, course_description, course_link, course_name, course_size, is_enabled, course_category_id) values (100, '1KcNUhHbDkhfb96aEF3F5hr3yZXPWRYfG9', 'http://dummyimage.com/197x100.png/cc0000/ffffff', 'Fear Clinic', 100, false, 100);



-- COURSE_CATEGORY
insert into course_category (id, category_name) values (1, 'Documentary');
insert into course_category (id, category_name) values (2, 'Horror');
insert into course_category (id, category_name) values (3, 'Drama|Romance');
insert into course_category (id, category_name) values (4, 'Drama');
insert into course_category (id, category_name) values (5, 'Comedy');
insert into course_category (id, category_name) values (6, 'Horror|Thriller');
insert into course_category (id, category_name) values (7, 'Animation|Children|Musical');
insert into course_category (id, category_name) values (8, 'Action|Comedy|Drama');
insert into course_category (id, category_name) values (9, 'Action|Comedy|Horror');
insert into course_category (id, category_name) values (10, 'Drama|Romance');
insert into course_category (id, category_name) values (11, 'Comedy|Horror');
insert into course_category (id, category_name) values (12, 'Action|Comedy');
insert into course_category (id, category_name) values (13, 'Crime|Drama|Mystery');
insert into course_category (id, category_name) values (14, 'Drama|Mystery|Thriller');
insert into course_category (id, category_name) values (15, 'Comedy');
insert into course_category (id, category_name) values (16, 'Comedy');
insert into course_category (id, category_name) values (17, 'Crime|Thriller');
insert into course_category (id, category_name) values (18, 'Drama');
insert into course_category (id, category_name) values (19, 'Comedy|Western');
insert into course_category (id, category_name) values (20, 'Animation|Drama|War');
insert into course_category (id, category_name) values (21, 'Comedy|War');
insert into course_category (id, category_name) values (22, 'Comedy');
insert into course_category (id, category_name) values (23, 'Comedy|Horror');
insert into course_category (id, category_name) values (24, 'Documentary');
insert into course_category (id, category_name) values (25, 'Action|Adventure|Fantasy|Sci-Fi');
insert into course_category (id, category_name) values (26, 'Action|Drama|Thriller');
insert into course_category (id, category_name) values (27, 'Drama');
insert into course_category (id, category_name) values (28, 'Comedy|Crime');
insert into course_category (id, category_name) values (29, 'Horror');
insert into course_category (id, category_name) values (30, 'Drama');
insert into course_category (id, category_name) values (31, 'Crime');
insert into course_category (id, category_name) values (32, 'Drama|Romance');
insert into course_category (id, category_name) values (33, 'Crime|Drama|Romance');
insert into course_category (id, category_name) values (34, 'Action|Crime|Drama');
insert into course_category (id, category_name) values (35, 'Documentary');
insert into course_category (id, category_name) values (36, 'Drama');
insert into course_category (id, category_name) values (37, 'Action|Comedy|Thriller');
insert into course_category (id, category_name) values (38, 'Drama');
insert into course_category (id, category_name) values (39, 'Drama|Horror|Mystery');
insert into course_category (id, category_name) values (40, 'Comedy|Crime');
insert into course_category (id, category_name) values (41, 'Action|Mystery|Thriller');
insert into course_category (id, category_name) values (42, 'Animation|Children');
insert into course_category (id, category_name) values (43, 'Action|Thriller');
insert into course_category (id, category_name) values (44, 'Drama|Horror|Romance');
insert into course_category (id, category_name) values (45, 'Comedy|Western');
insert into course_category (id, category_name) values (46, 'Action|Comedy');
insert into course_category (id, category_name) values (47, 'Comedy|Drama');
insert into course_category (id, category_name) values (48, 'Comedy|Romance');
insert into course_category (id, category_name) values (49, 'Crime|Horror');
insert into course_category (id, category_name) values (50, 'Comedy|Fantasy');
insert into course_category (id, category_name) values (51, 'Action|Comedy|Western');
insert into course_category (id, category_name) values (52, 'Children');
insert into course_category (id, category_name) values (53, 'Thriller');
insert into course_category (id, category_name) values (54, 'Action|Musical|Sci-Fi');
insert into course_category (id, category_name) values (55, 'Drama|Romance');
insert into course_category (id, category_name) values (56, 'Action|Adventure');
insert into course_category (id, category_name) values (57, 'Drama');
insert into course_category (id, category_name) values (58, 'Comedy');
insert into course_category (id, category_name) values (59, 'Comedy|Drama');
insert into course_category (id, category_name) values (60, 'Comedy');
insert into course_category (id, category_name) values (61, 'Comedy');
insert into course_category (id, category_name) values (62, 'Western');
insert into course_category (id, category_name) values (63, 'Comedy|Drama|Fantasy|Romance');
insert into course_category (id, category_name) values (64, 'Action|Comedy|Fantasy');
insert into course_category (id, category_name) values (65, 'Comedy');
insert into course_category (id, category_name) values (66, 'Drama');
insert into course_category (id, category_name) values (67, 'Drama');
insert into course_category (id, category_name) values (68, 'Documentary');
insert into course_category (id, category_name) values (69, 'Comedy');
insert into course_category (id, category_name) values (70, 'Drama');
insert into course_category (id, category_name) values (71, '(no genres listed)');
insert into course_category (id, category_name) values (72, 'Drama|Mystery');
insert into course_category (id, category_name) values (73, 'Drama|Romance|Thriller|War');
insert into course_category (id, category_name) values (74, 'Action|Adventure|Thriller');
insert into course_category (id, category_name) values (75, 'Documentary');
insert into course_category (id, category_name) values (76, 'Comedy');
insert into course_category (id, category_name) values (77, 'Romance|Western');
insert into course_category (id, category_name) values (78, 'Children');
insert into course_category (id, category_name) values (79, 'Drama|Romance');
insert into course_category (id, category_name) values (80, 'Drama|Sci-Fi');
insert into course_category (id, category_name) values (81, 'Action|Adventure|Drama');
insert into course_category (id, category_name) values (82, 'Animation|Fantasy|Mystery');
insert into course_category (id, category_name) values (83, 'Drama|Romance');
insert into course_category (id, category_name) values (84, 'Drama');
insert into course_category (id, category_name) values (85, 'Drama');
insert into course_category (id, category_name) values (86, 'Adventure|Comedy');
insert into course_category (id, category_name) values (87, 'Comedy|Romance');
insert into course_category (id, category_name) values (88, 'Horror|Mystery|Sci-Fi|Thriller');
insert into course_category (id, category_name) values (89, 'Drama');
insert into course_category (id, category_name) values (90, 'Drama');
insert into course_category (id, category_name) values (91, 'Crime|Drama|Horror|Musical');
insert into course_category (id, category_name) values (92, 'Comedy');
insert into course_category (id, category_name) values (93, 'Drama');
insert into course_category (id, category_name) values (94, 'Action|Adventure|Sci-Fi');
insert into course_category (id, category_name) values (95, 'Fantasy|Romance');
insert into course_category (id, category_name) values (96, 'Drama|Film-Noir|Thriller');
insert into course_category (id, category_name) values (97, 'Drama|Romance');
insert into course_category (id, category_name) values (98, '(no genres listed)');
insert into course_category (id, category_name) values (99, 'Comedy');
insert into course_category (id, category_name) values (100, 'Horror');


